apiVersion: v1
kind: Secret

metadata:
  # name: private-repo
  name: public-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: git@github.com:rodolfoHOk/rocketseat.nlw-unite.git
  # sshPrivateKey: |
  #   -----BEGIN OPENSSH PRIVATE KEY-----
  #   -----END OPENSSH PRIVATE KEY-----
  # acima para repositórios privados
