name: CI

on:
  push:
    paths:
      - 'server/**'
      - 'devops/deploy/**'
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t rodolfohok/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} ./server

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push rodolfohok/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}
          docker tag rodolfohok/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} rodolfohok/nlw.service.passin:latest
          docker push rodolfohok/nlw.service.passin:latest

      - name: Update image tag
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: main
          valueFile: 'devops/deploy/values.yaml'
          propertyPath: 'image.tag'
          value: '${{ steps.generate_sha.outputs.sha }}'
          commitChange: true
          message: 'NEW: Update tag in values helm'
